-- MySQL Script generated by MySQL Workbench
-- Tue Feb 28 14:12:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema students
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema students
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `students` DEFAULT CHARACTER SET utf8 ;
USE `students` ;

-- -----------------------------------------------------
-- Table `students`.`ИИН`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students`.`ИИН` (
  `idИИН` INT NOT NULL,
  `0000001` VARCHAR(45) NOT NULL,
  `0000002` VARCHAR(45) NOT NULL,
  `0000003` VARCHAR(45) NOT NULL,
  `0000004` VARCHAR(45) NOT NULL,
  `0000005` VARCHAR(45) NOT NULL,
  `0000009` VARCHAR(45) NOT NULL,
  `0000006` VARCHAR(45) NOT NULL,
  `0000007` VARCHAR(45) NOT NULL,
  `ИИНcol4` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idИИН`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students`.`nameuser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students`.`nameuser` (
  `idtable1` INT NOT NULL,
  `Акимжанов Хусан` VARCHAR(45) NOT NULL,
  `Акимжанов Хасан` VARCHAR(45) NOT NULL,
  `Бораш Сержан` VARCHAR(45) NOT NULL,
  `Куйчибаев Санжарали` VARCHAR(45) NOT NULL,
  `Назаров Нурадилет` VARCHAR(45) NOT NULL,
  `Муратов Нодир` VARCHAR(45) NOT NULL,
  `Досай Акжунис` VARCHAR(45) NOT NULL,
  `Тулепбек Сержан` VARCHAR(45) NOT NULL,
  `Алиханов Давлат` VARCHAR(45) NOT NULL,
  `ИИН_idИИН` INT NOT NULL,
  PRIMARY KEY (`idtable1`, `ИИН_idИИН`),
  INDEX `fk_nameuser_ИИН1_idx` (`ИИН_idИИН` ASC) VISIBLE,
  CONSTRAINT `fk_nameuser_ИИН1`
    FOREIGN KEY (`ИИН_idИИН`)
    REFERENCES `students`.`ИИН` (`idИИН`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students`.`lessons` (
  `idlessons` INT NOT NULL,
  `Философия` VARCHAR(45) NOT NULL,
  `Физкультура` VARCHAR(45) NOT NULL,
  `Ясауитану` VARCHAR(45) NOT NULL,
  `Кәсіби цифрлық технологияр` VARCHAR(45) NOT NULL,
  `Желілер және желілік технологияр` VARCHAR(45) NOT NULL,
  `Ақпараттық жүйелердегі мәліметтер базасы` VARCHAR(45) NOT NULL,
  `Түркі мемлекеттер тарихы` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlessons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `students`.`nameuser_has_lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `students`.`nameuser_has_lessons` (
  `nameuser_idtable1` INT NOT NULL,
  `lessons_idlessons` INT NOT NULL,
  PRIMARY KEY (`nameuser_idtable1`, `lessons_idlessons`),
  INDEX `fk_nameuser_has_lessons_lessons1_idx` (`lessons_idlessons` ASC) VISIBLE,
  INDEX `fk_nameuser_has_lessons_nameuser_idx` (`nameuser_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_nameuser_has_lessons_nameuser`
    FOREIGN KEY (`nameuser_idtable1`)
    REFERENCES `students`.`nameuser` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nameuser_has_lessons_lessons1`
    FOREIGN KEY (`lessons_idlessons`)
    REFERENCES `students`.`lessons` (`idlessons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
