# Generated by Django 4.2 on 2023-05-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fakulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fakulty')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('code', models.CharField(default='', max_length=40, unique=True)),
                ('fakulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fakulty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('iin', models.CharField(max_length=12)),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], max_length=1)),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
            ],
        ),
        migrations.CreateModel(
            name='SRStwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week8', models.IntegerField()),
                ('week9', models.IntegerField()),
                ('week10', models.IntegerField()),
                ('week11', models.IntegerField()),
                ('week12', models.IntegerField()),
                ('week13', models.IntegerField()),
                ('week14', models.IntegerField()),
                ('week15', models.IntegerField()),
                ('SRS_2', models.IntegerField(default=0)),
                ('result2', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='SRSone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week1', models.IntegerField()),
                ('week2', models.IntegerField()),
                ('week3', models.IntegerField()),
                ('week4', models.IntegerField()),
                ('week5', models.IntegerField()),
                ('week6', models.IntegerField()),
                ('week7', models.IntegerField()),
                ('SRS_1', models.IntegerField(default=0)),
                ('result', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_grade', models.IntegerField()),
                ('final_result2', models.FloatField(blank=True, null=True)),
                ('SRS_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.srsone')),
                ('SRS_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.srstwo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
    ]
