# Generated by Django 4.2 on 2023-10-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_gpa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курс'},
        ),
        migrations.AlterModelOptions(
            name='fakulty',
            options={'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='finalresult',
            options={'verbose_name': 'Оценка за экзамен', 'verbose_name_plural': 'Оценка за экзамены'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='srsone',
            options={'verbose_name': 'СРС - 1', 'verbose_name_plural': 'СРС - 1'},
        ),
        migrations.AlterModelOptions(
            name='srstwo',
            options={'verbose_name': 'СРС - 2', 'verbose_name_plural': 'СРС - 2'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя: ')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('iin', models.CharField(max_length=12, verbose_name='ИИН: ')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('W', 'Женский')], max_length=1, verbose_name='Пол: ')),
                ('url', models.SlugField(max_length=100, unique=True, verbose_name='Уникальный адресс:')),
                ('group', models.ManyToManyField(related_name='group', to='main.group', verbose_name='Группы: ')),
                ('subject', models.ManyToManyField(related_name='subject', to='main.subject', verbose_name='Предметы')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
    ]
