# Generated by Django 4.2 on 2023-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_user_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='link',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
