# Generated by Django 4.2 on 2023-11-11 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_group_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final', models.ManyToManyField(to='main.finalresult')),
                ('first', models.ManyToManyField(related_name='srs_one', to='main.srsone')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group')),
                ('second', models.ManyToManyField(related_name='srs_two', to='main.srstwo')),
                ('students', models.ManyToManyField(related_name='students', to='main.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher')),
            ],
            options={
                'verbose_name': 'Оценка группы',
                'verbose_name_plural': 'Оценки группы',
            },
        ),
    ]
